---
comment_days: 30
comments: comments/good/
db: blog.sqlite
format: markdown
frontpage_posts: 10
org: /usr/share/emacs/23.4/lisp/org/org.elc
postfile: archive/%Y/%m/POST
source: entries/
rss_posts: 10
rss_comments: 50
tagdir: tags/
target: out/
template: template/
title: "CHANGEME_BLOG_NAME"
top_ext: CHANGEME_URL_TO_BLOG_ROOT
top_int: /
